### ISSUE TITLE
SZ stopped fetching new subs, and it's not recognizing manually inserted subs

### ISSUE THREAD

**Issue by pguizeline** [pannal/Sub-Zero.bundle#348]
Hi,

I'm at a loss here, it seems that I have no permission errors, everything was working ok, but SZ seems to have stopped working after the latest Plex update.

Here's are my logs:
https://ghostbin.com/paste/xap2k

Another strange behavior is when I query "Items with missing subtitles", it seems that SZ is not altering that list and subtitles are being downloaded over and over again.

Thanks in advance and please let me know how I can help.

**Comment by ThatFatPat** [comment]
+1

**Comment by pannal** [comment]
Sorry for the long response time. 

This might partially be related to #352.

Another ping to @opensubtitles :)

The other error I see in your logs are TVDB related. I'll investigate.

**Comment by opensubtitles** [comment]
not sure what to comment, here it is working, please try @pannal at your side

**Comment by pannal** [comment]
@pguizeline is this still an issue?

**Comment by ThatFatPat** [comment]
Yes.

**Comment by pannal** [comment]
So you still have connection issues to OpenSubtitles? Do you use a seedbox?

**Comment by pannal** [comment]
SZ uses the subliminal dev branch. Your issues are resolved now?

**Comment by pguizeline** [comment]
Subliminal dev works partially for me, but I think they are working on lots of bugs, I get the following errors:
https://github.com/Diaoul/subliminal/issues/761
https://github.com/Diaoul/subliminal/pull/800

But they are not yet fixed and are not Sub-Zero's fault :)

**Comment by pannal** [comment]
Both of those have been fixed in the current SZ release and are unrelated to your issue you've created this ticket about.

I'd really get to resolving this, as you may not be the only affected user.

**Comment by pguizeline** [comment]
Just tested SZ and it's working! Sorry for all the trouble!

**Comment by pannal** [comment]
Great!
