### ISSUE TITLE
English subs downloaded by SZ shows as 'Unknown' in PMS

### ISSUE THREAD

**Issue by BeyondEvil** [pannal/Sub-Zero.bundle#435]
I have an issue where English subtitles downloaded by sub-zero turns up as 'Unknown' in Plex Media Server.

I have two servers. One running on OSX and one running on CentOS. Both have the same issue. Both run latest of both PMS and SZ.

Update 1:

I tried renaming the srt-file to have .en and .eng in it - and that worked.

So the question then becomes - why doesn't SZ handle this when it knows the language that it's downloading for me? I can't find a setting to control this...

Update 2:

Found the offending setting: "Restrict to one language (skips adding ".lang." to the subtitle filename; only uses "Subtitle Language (1)") "

I had that enabled. So is this a bug or working by design? I have it enabled for a reason, I only want English subtitles. And I interpret it as the latter part ("only uses "Subtitle Language (1)") as it should still rename the file to reflect that setting?

**Comment by pannal** [comment]
It's a bug and it's fixed in the upcoming version 2.5.

Thanks for reporting :)

**Comment by ChrisColotti** [comment]
Installed and running 2.5.0.2247 and this still seems to  be an issue.  With the 
"Restrict to one language (skips adding ".lang." to the subtitle filename; only uses "Subtitle Language (1)") "

Still getting all unknown on english subs.

**Comment by pannal** [comment]
Interesting. Can I see some logs?

**Comment by ChrisColotti** [comment]
[Logs_180303_07-32-39.zip](https://github.com/pannal/Sub-Zero.bundle/files/1777473/Logs_180303_07-32-39.zip)

**Comment by pannal** [comment]
Hmm, the log is full of provider errors, I can't really make anything out. Can you set SZ's log level to DEBUG, then refresh an item in question, then post the logs again?

**Comment by ChrisColotti** [comment]
Enabled debug and checked the box.  Use "The Shape of Water" as the search that is the one I refreshed and yes it grabbed it and did not add the .en tag to it with the box checked.   If I remove the selection it will add the .en and plex sees it as English correctly.

Should also be easy to reproduce.  I also have radarr and sonarr API addresses configured.

[Logs_180303_08-07-04.zip](https://github.com/pannal/Sub-Zero.bundle/files/1777487/Logs_180303_08-07-04.zip)

**Comment by pannal** [comment]
I can't find any info about that specific movie in the logs, unfortunately. Found another bug and fixed that, though (unrelated).

Can you refresh it again and grab the logs maybe a minute later?
