### ISSUE TITLE
Addic7ed: AuthenticationError

### ISSUE THREAD

**Issue by MichaelSoe** [pannal/Sub-Zero.bundle#612]
Since a short while I don't see any results for subtitles from Addic7ed when I searched manually. I didn't think much of it at first,  but now I've looked into the issue and even when Addic7ed has subtitles for the series that I'm looking for, they aren't displayed in the results and aren't downloaded.

When looking in the logs, I see that there's an authentication error when SZ tries to login. I've no idea why or when this suddenly started, but this used to work. I've double checked my credentials, but I didn't find a solution.

I've attached my logs.

Thanks in advance for any help you're able to give!

[Logs_190119_13-42-34.zip](https://github.com/pannal/Sub-Zero.bundle/files/2775492/Logs_190119_13-42-34.zip)

**Comment by pannal** [comment]
Please re-add your correct credentials. Credentials haven't been used for a couple of months due to a bug, which has been resolved with the last release. It might be that they were never used in your instance in the first place.

**Comment by viking1304** [comment]
I had same problem last night. I entered user and password again and it works now.
Also, be sure to use username and not e-mail address as username. I changed that and it works now.

**Comment by MichaelSoe** [comment]
I've tried that, but to no avail. I've removed my credentials, saved the configuration, restarted the plugin. Disabled en re-enabled the Addic7ed provider and again restarted the plugin, but I still receive the same error. I've even copy pasted my login and password, to make sure I didn't make any typing error.

**Comment by pannal** [comment]
Weird. Do you have a password manager or autofill enabled?

**Comment by Killertjuh** [comment]
> Weird. Do you have a password manager or autofill enabled?

```2019-03-13 07:55:28,050 (7f4059ffb700) :  ERROR (logger:36) - subliminal_patch.core: Unexpected error in provider 'addic7ed': Traceback (most recent call last):
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 162, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 99, in __getitem__
    provider.initialize()
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/addic7ed.py", line 110, in initialize
    raise AuthenticationError(self.username)
AuthenticationError: usernamehidden```

Same issue after entered username and  password. I dont use passwordmanager for this.

**Comment by pannal** [comment]
Maybe they've changed their auth mechanism again. I'll investigate.

**Comment by ferllings** [comment]
Same issue.
For info I have the same problem with Bazarr.

**Comment by pannal** [comment]
Yep, they've added captchas, [instead of actually talking](https://github.com/pannal/Sub-Zero.bundle/issues/490) to me.

**Comment by cphmichael** [comment]
It seems like I have the same problem.

It that something that is possible to solve?

- - - - -

2019-03-28 12:09:22,940 (1481348aa700) :  INFO (logger:38) - subliminal_patch.providers.addic7ed: Addic7ed: Logging in
2019-03-28 12:09:22,940 (148134ead700) :  DEBUG (logger:28) - subliminal_patch.providers.subscene: Filter created: '{'LanguageFilter': '13', 'HearingImpaired': '2'}'
2019-03-28 12:09:22,942 (148134aab700) :  DEBUG (logger:28) - subliminal_patch.providers.opensubtitles: Trying previous token: 'mVYQrJwTWSXXXXXXXXXXXXXXXXX'
2019-03-28 12:09:22,943 (148134ead700) :  DEBUG (logger:28) - subliminal_patch.providers.subscene: Filters applied
2019-03-28 12:09:22,945 (148134ead700) :  DEBUG (logger:28) - subliminal_patch.providers.subscene: Searching for: Lethal Weapon - S01E01 - Pilot
2019-03-28 12:09:22,995 (1481348aa700) :  ERROR (logger:38) - subliminal_patch.core: Unexpected error in provider 'addic7ed': Traceback (most recent call last):
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 162, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 99, in __getitem__
    provider.initialize()
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/addic7ed.py", line 110, in initialize
    raise AuthenticationError(self.username)
AuthenticationError: cphmichael

- - - - -
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/3017650/com.plexapp.agents.subzero.log)

**Comment by ThomasClemenceau** [comment]
@pannal 
Hey !

Do you have any news about addic7ed ?

**Comment by pannal** [comment]
Not really. They've locked us out by using reCAPTCHA upon login/show-list.

**Comment by ThomasClemenceau** [comment]
Did they not create API to use instead ?

**Comment by pannal** [comment]
Nope, at least not yet. It's been planned for ages.

**Comment by ThomasClemenceau** [comment]
I actually have open a topic on the addic7ed forum :
http://www.sub-talk.net/topic/7806-api-for-software-usage/

We will see their answers

**Comment by ThomasClemenceau** [comment]
The answer is : "For the moment, a reCaptcha v2 was implemented on the login page. We're also working on an API to make things easier for people that want to automate subtitle downloads (and uploads!). More info soon."

**Comment by ThomasClemenceau** [comment]
@pannal 
Just seen the label "fixed in upcoming version" but tried with the dev branch and addic7ed is removed. Is it normal ?

**Comment by pannal** [comment]
Where is it removed? It should be in the settings. But it needs a configured anticaptcha service to actually be used.

**Comment by ThomasClemenceau** [comment]
Oh my bad, was not on the right branch (checkout failed). It works. I have no anticaptcha account to test but it's in settings. I will wait for addic7ed to change its system
